export type SeedAsset = {
  symbol: string;
  label: string;
  category: string;
  basePrice: number;
  precision: number;
  payoutBoost: number;
};

export const OTC_TIMEFRAME = 'M1';
export const M1_CANDLE_MS = 60_000;
export const DEFAULT_CANDLE_LIMIT = 120;
export const MAX_CANDLE_LIMIT = 500;

export const OTC_ASSETS: SeedAsset[] = [
  /*
    =========================
    CURRENCIES
    =========================
  */
  {
    symbol: 'AUD/CAD OTC',
    label: 'Australian Dollar / Canadian Dollar',
    category: 'Currencies',
    basePrice: 0.8421,
    precision: 5,
    payoutBoost: 7,
  },
  {
    symbol: 'EUR/USD OTC',
    label: 'Euro / US Dollar',
    category: 'Currencies',
    basePrice: 1.0845,
    precision: 5,
    payoutBoost: 5,
  },
  {
    symbol: 'USD/JPY OTC',
    label: 'US Dollar / Japanese Yen',
    category: 'Currencies',
    basePrice: 157.45,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: 'GBP/USD OTC',
    label: 'British Pound / US Dollar',
    category: 'Currencies',
    basePrice: 1.2685,
    precision: 5,
    payoutBoost: 5,
  },
  {
    symbol: 'USD/CHF OTC',
    label: 'US Dollar / Swiss Franc',
    category: 'Currencies',
    basePrice: 0.8954,
    precision: 5,
    payoutBoost: 5,
  },
  {
    symbol: 'USD/CAD OTC',
    label: 'US Dollar / Canadian Dollar',
    category: 'Currencies',
    basePrice: 1.3712,
    precision: 5,
    payoutBoost: 5,
  },
  {
    symbol: 'AUD/USD OTC',
    label: 'Australian Dollar / US Dollar',
    category: 'Currencies',
    basePrice: 0.6624,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'NZD/USD OTC',
    label: 'New Zealand Dollar / US Dollar',
    category: 'Currencies',
    basePrice: 0.6118,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/GBP OTC',
    label: 'Euro / British Pound',
    category: 'Currencies',
    basePrice: 0.8551,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/JPY OTC',
    label: 'Euro / Japanese Yen',
    category: 'Currencies',
    basePrice: 170.42,
    precision: 3,
    payoutBoost: 5,
  },
  {
    symbol: 'GBP/JPY OTC',
    label: 'British Pound / Japanese Yen',
    category: 'Currencies',
    basePrice: 199.28,
    precision: 3,
    payoutBoost: 5,
  },
  {
    symbol: 'AUD/JPY OTC',
    label: 'Australian Dollar / Japanese Yen',
    category: 'Currencies',
    basePrice: 104.05,
    precision: 3,
    payoutBoost: 6,
  },
  {
    symbol: 'CAD/JPY OTC',
    label: 'Canadian Dollar / Japanese Yen',
    category: 'Currencies',
    basePrice: 114.82,
    precision: 3,
    payoutBoost: 6,
  },
  {
    symbol: 'CHF/JPY OTC',
    label: 'Swiss Franc / Japanese Yen',
    category: 'Currencies',
    basePrice: 175.88,
    precision: 3,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/AUD OTC',
    label: 'Euro / Australian Dollar',
    category: 'Currencies',
    basePrice: 1.6376,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'GBP/AUD OTC',
    label: 'British Pound / Australian Dollar',
    category: 'Currencies',
    basePrice: 1.9158,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/CAD OTC',
    label: 'Euro / Canadian Dollar',
    category: 'Currencies',
    basePrice: 1.4868,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'GBP/CAD OTC',
    label: 'British Pound / Canadian Dollar',
    category: 'Currencies',
    basePrice: 1.7394,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'AUD/NZD OTC',
    label: 'Australian Dollar / New Zealand Dollar',
    category: 'Currencies',
    basePrice: 1.0829,
    precision: 5,
    payoutBoost: 7,
  },
  {
    symbol: 'EUR/NZD OTC',
    label: 'Euro / New Zealand Dollar',
    category: 'Currencies',
    basePrice: 1.7729,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'GBP/NZD OTC',
    label: 'British Pound / New Zealand Dollar',
    category: 'Currencies',
    basePrice: 2.0735,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'NZD/JPY OTC',
    label: 'New Zealand Dollar / Japanese Yen',
    category: 'Currencies',
    basePrice: 96.24,
    precision: 3,
    payoutBoost: 6,
  },
  {
    symbol: 'USD/MXN OTC',
    label: 'US Dollar / Mexican Peso',
    category: 'Currencies',
    basePrice: 18.245,
    precision: 4,
    payoutBoost: 7,
  },
  {
    symbol: 'USD/ZAR OTC',
    label: 'US Dollar / South African Rand',
    category: 'Currencies',
    basePrice: 18.21,
    precision: 4,
    payoutBoost: 7,
  },
  {
    symbol: 'USD/TRY OTC',
    label: 'US Dollar / Turkish Lira',
    category: 'Currencies',
    basePrice: 32.84,
    precision: 4,
    payoutBoost: 7,
  },
  {
    symbol: 'USD/SGD OTC',
    label: 'US Dollar / Singapore Dollar',
    category: 'Currencies',
    basePrice: 1.3524,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'USD/HKD OTC',
    label: 'US Dollar / Hong Kong Dollar',
    category: 'Currencies',
    basePrice: 7.8125,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/CHF OTC',
    label: 'Euro / Swiss Franc',
    category: 'Currencies',
    basePrice: 0.9708,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'CAD/CHF OTC',
    label: 'Canadian Dollar / Swiss Franc',
    category: 'Currencies',
    basePrice: 0.6529,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'AUD/CHF OTC',
    label: 'Australian Dollar / Swiss Franc',
    category: 'Currencies',
    basePrice: 0.5932,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'NZD/CHF OTC',
    label: 'New Zealand Dollar / Swiss Franc',
    category: 'Currencies',
    basePrice: 0.5476,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'EUR/TRY OTC',
    label: 'Euro / Turkish Lira',
    category: 'Currencies',
    basePrice: 35.62,
    precision: 4,
    payoutBoost: 7,
  },
  {
    symbol: 'EUR/ZAR OTC',
    label: 'Euro / South African Rand',
    category: 'Currencies',
    basePrice: 19.76,
    precision: 4,
    payoutBoost: 7,
  },
  {
    symbol: 'GBP/CHF OTC',
    label: 'British Pound / Swiss Franc',
    category: 'Currencies',
    basePrice: 1.1358,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'GBP/SGD OTC',
    label: 'British Pound / Singapore Dollar',
    category: 'Currencies',
    basePrice: 1.7148,
    precision: 5,
    payoutBoost: 6,
  },
  {
    symbol: 'USD/KES OTC',
    label: 'US Dollar / Kenyan Shilling',
    category: 'Currencies',
    basePrice: 129.5,
    precision: 3,
    payoutBoost: 7,
  },

  /*
    =========================
    CRYPTOCURRENCIES
    =========================
  */
  {
    symbol: 'BTC/USD OTC',
    label: 'Bitcoin / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 68200,
    precision: 2,
    payoutBoost: 1,
  },
  {
    symbol: 'ETH/USD OTC',
    label: 'Ethereum / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 3550,
    precision: 2,
    payoutBoost: 2,
  },
  {
    symbol: 'BNB/USD OTC',
    label: 'BNB / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 605,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'SOL/USD OTC',
    label: 'Solana / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 145,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'XRP/USD OTC',
    label: 'XRP / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.526,
    precision: 5,
    payoutBoost: 4,
  },
  {
    symbol: 'ADA/USD OTC',
    label: 'Cardano / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.418,
    precision: 5,
    payoutBoost: 4,
  },
  {
    symbol: 'DOGE/USD OTC',
    label: 'Dogecoin / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.124,
    precision: 5,
    payoutBoost: 4,
  },
  {
    symbol: 'TRX/USD OTC',
    label: 'TRON / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.118,
    precision: 5,
    payoutBoost: 4,
  },
  {
    symbol: 'DOT/USD OTC',
    label: 'Polkadot / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 6.35,
    precision: 4,
    payoutBoost: 4,
  },
  {
    symbol: 'LTC/USD OTC',
    label: 'Litecoin / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 78.4,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'BCH/USD OTC',
    label: 'Bitcoin Cash / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 432,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'AVAX/USD OTC',
    label: 'Avalanche / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 31.8,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: 'LINK/USD OTC',
    label: 'Chainlink / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 14.9,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: 'MATIC/USD OTC',
    label: 'Polygon / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.72,
    precision: 5,
    payoutBoost: 4,
  },
  {
    symbol: 'ATOM/USD OTC',
    label: 'Cosmos / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 7.18,
    precision: 4,
    payoutBoost: 4,
  },
  {
    symbol: 'UNI/USD OTC',
    label: 'Uniswap / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 9.2,
    precision: 4,
    payoutBoost: 4,
  },
  {
    symbol: 'AAVE/USD OTC',
    label: 'Aave / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 92.5,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'XLM/USD OTC',
    label: 'Stellar / US Dollar',
    category: 'Cryptocurrencies',
    basePrice: 0.106,
    precision: 5,
    payoutBoost: 4,
  },

  /*
    =========================
    STOCKS
    =========================
  */
  {
    symbol: 'Tesla OTC',
    label: 'Tesla Inc.',
    category: 'Stocks',
    basePrice: 181.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Apple OTC',
    label: 'Apple Inc.',
    category: 'Stocks',
    basePrice: 214.2,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Amazon OTC',
    label: 'Amazon.com Inc.',
    category: 'Stocks',
    basePrice: 185.6,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Microsoft OTC',
    label: 'Microsoft Corporation',
    category: 'Stocks',
    basePrice: 425.3,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Nvidia OTC',
    label: 'NVIDIA Corporation',
    category: 'Stocks',
    basePrice: 126.8,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Meta OTC',
    label: 'Meta Platforms Inc.',
    category: 'Stocks',
    basePrice: 498.7,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Alphabet A OTC',
    label: 'Alphabet Inc. Class A',
    category: 'Stocks',
    basePrice: 176.2,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Netflix OTC',
    label: 'Netflix Inc.',
    category: 'Stocks',
    basePrice: 645.9,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'AMD OTC',
    label: 'Advanced Micro Devices Inc.',
    category: 'Stocks',
    basePrice: 162.5,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Intel OTC',
    label: 'Intel Corporation',
    category: 'Stocks',
    basePrice: 31.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'IBM OTC',
    label: 'International Business Machines',
    category: 'Stocks',
    basePrice: 184.8,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Oracle OTC',
    label: 'Oracle Corporation',
    category: 'Stocks',
    basePrice: 138.2,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Adobe OTC',
    label: 'Adobe Inc.',
    category: 'Stocks',
    basePrice: 525.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Salesforce OTC',
    label: 'Salesforce Inc.',
    category: 'Stocks',
    basePrice: 251.6,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'PayPal OTC',
    label: 'PayPal Holdings Inc.',
    category: 'Stocks',
    basePrice: 64.8,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Coca-Cola OTC',
    label: 'The Coca-Cola Company',
    category: 'Stocks',
    basePrice: 63.2,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'McDonalds OTC',
    label: "McDonald's Corporation",
    category: 'Stocks',
    basePrice: 257.9,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Visa OTC',
    label: 'Visa Inc.',
    category: 'Stocks',
    basePrice: 276.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'JPMorgan OTC',
    label: 'JPMorgan Chase & Co.',
    category: 'Stocks',
    basePrice: 201.5,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'ExxonMobil OTC',
    label: 'Exxon Mobil Corporation',
    category: 'Stocks',
    basePrice: 113.8,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Walmart OTC',
    label: 'Walmart Inc.',
    category: 'Stocks',
    basePrice: 67.4,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Alibaba OTC',
    label: 'Alibaba Group Holding Ltd.',
    category: 'Stocks',
    basePrice: 76.6,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Toyota OTC',
    label: 'Toyota Motor Corporation',
    category: 'Stocks',
    basePrice: 198.5,
    precision: 2,
    payoutBoost: 3,
  },
  {
    symbol: 'Samsung OTC',
    label: 'Samsung Electronics',
    category: 'Stocks',
    basePrice: 54.2,
    precision: 2,
    payoutBoost: 3,
  },

  /*
    =========================
    INDICES
    =========================
  */
  {
    symbol: 'US100 OTC',
    label: 'Nasdaq 100',
    category: 'Indices',
    basePrice: 19888.46,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'US30 OTC',
    label: 'Dow Jones 30',
    category: 'Indices',
    basePrice: 38950.9,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'SPX500 OTC',
    label: 'S&P 500',
    category: 'Indices',
    basePrice: 5460.2,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'UK100 OTC',
    label: 'FTSE 100',
    category: 'Indices',
    basePrice: 8210.5,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'GER40 OTC',
    label: 'Germany 40',
    category: 'Indices',
    basePrice: 18435.4,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'FRA40 OTC',
    label: 'France 40',
    category: 'Indices',
    basePrice: 7630.6,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'EU50 OTC',
    label: 'Euro Stoxx 50',
    category: 'Indices',
    basePrice: 4925.8,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'JPN225 OTC',
    label: 'Japan 225',
    category: 'Indices',
    basePrice: 38650.7,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'HK50 OTC',
    label: 'Hong Kong 50',
    category: 'Indices',
    basePrice: 18120.4,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'AUS200 OTC',
    label: 'Australia 200',
    category: 'Indices',
    basePrice: 7820.3,
    precision: 2,
    payoutBoost: 4,
  },

  /*
    =========================
    COMMODITIES
    =========================
  */
  {
    symbol: 'XAU/USD OTC',
    label: 'Gold / US Dollar',
    category: 'Commodities',
    basePrice: 2322.4,
    precision: 2,
    payoutBoost: 5,
  },
  {
    symbol: 'XAG/USD OTC',
    label: 'Silver / US Dollar',
    category: 'Commodities',
    basePrice: 29.15,
    precision: 3,
    payoutBoost: 5,
  },
  {
    symbol: 'Brent OTC',
    label: 'Brent Crude Oil',
    category: 'Commodities',
    basePrice: 82.8,
    precision: 2,
    payoutBoost: 2,
  },
  {
    symbol: 'WTI OTC',
    label: 'West Texas Intermediate Oil',
    category: 'Commodities',
    basePrice: 78.2,
    precision: 2,
    payoutBoost: 2,
  },
  {
    symbol: 'Natural Gas OTC',
    label: 'Natural Gas',
    category: 'Commodities',
    basePrice: 2.85,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: 'Copper OTC',
    label: 'Copper',
    category: 'Commodities',
    basePrice: 4.52,
    precision: 3,
    payoutBoost: 4,
  },
  {
    symbol: 'Platinum OTC',
    label: 'Platinum',
    category: 'Commodities',
    basePrice: 1015.4,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'Palladium OTC',
    label: 'Palladium',
    category: 'Commodities',
    basePrice: 945.8,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'Corn OTC',
    label: 'Corn',
    category: 'Commodities',
    basePrice: 445.5,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'Wheat OTC',
    label: 'Wheat',
    category: 'Commodities',
    basePrice: 612.4,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'Soybeans OTC',
    label: 'Soybeans',
    category: 'Commodities',
    basePrice: 1165.2,
    precision: 2,
    payoutBoost: 4,
  },
  {
    symbol: 'Coffee OTC',
    label: 'Coffee',
    category: 'Commodities',
    basePrice: 224.7,
    precision: 2,
    payoutBoost: 4,
  },
];